apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata: 
  name: k8s-multi-hercax-net-tls
spec:
  secretName: k8s-multi-hercax-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-multi.hercax.net
  dnsNames:
    - k8s-multi.hercax.net
  acme:
    config:
      - http01: 
          ingressClass: nginx
          domains:
            - k8s-multi.hercax.net