apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata: 
  name: multi-k8s-hercax-net-tls
spec:
  secretName: multi-k8s-hercax-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.hercax.net
  dnsNames:
    - multi-k8s.hercax.net
  acme:
    config:
      - http01: 
          ingressClass: nginx
        domains:
          - multi-k8s.hercax.net