apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx   
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1    
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - multi-k8s.hercax.net
      secretName: multi-k8s-hercax-net
  rules:
    - host: multi-k8s.hercax.net
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
          - path: /?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 3000
          